# Generated by Django 4.1.5 on 2023-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quizcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmittedanswers',
            name='category',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
